config/routes.rb
Rails.application.routes.draw do
  root  'users#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :matching, only: [:index]
  get '/user/like', to: 'matching#like', as: :like
  get '/user/liked', to: 'matching#liked', as: :liked
  resources :messages, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
  validates_presence_of :following_id, :follower_id
end

app/models/user.rb
class User < ApplicationRecord
  scope :matching, -> user_id { joins("INNER JOIN relationships ON relationships.follower_id = users.id
  INNER JOIN relationships AS r ON relationships.following_id = r.follower_id AND r.following_id = relationships.follower_id").where('relationships.following_id = ?', user_id) }

  mount_uploader :avatar, AvatarUploader
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def following?(other_user)
    following.include?(other_user)
  end

  # ユーザーをフォローする
  # def follow(other_user)
  #   active_relationships.create(following_id: other_user.id)
  # end

  # ユーザーをアンフォローする
  # def unfollow(other_user)
  #   active_relationships.find_by(following_id: other_user.id).destroy
  # end

  # 現在のユーザーがフォローしてたらtrueを返す
  # def following?(other_user)
  #   following.include?(other_user)
  # end

  # def matching_users
  #   @users = []
  #   self.following.each do |user|
  #     if user.following?(self)
  #       @users << user
  #     end
  #   end
  # end

  def matchers
    following & followers
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :profile, :avatar])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create
    redirect_to :root
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  def index
    @users = current_user.matchers
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @your_messages = @user.messages.order("created_at DESC")
    @message = Message.new
    @my_messages = current_user.messages
    msg = @your_messages + @my_messages
    @messages = msg.sort{|a,b| a["created_at"] <=> b["created_at"]}
    # ここら辺のロジック汚いからなんとかしたい

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = current_user.messages.new(create_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      render :show
    end
  end

  private

  def create_params
    params.require(:message).permit(:body)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @relationship = current_user.active_relationships.new(create_params)
    if @relationship.save
      @follower_user = current_user
      @following_user = User.find(params["following_id"])
      @matching = @following_user.following?(current_user)
      # なんか汚いので、余裕あったらなんとかしたい

      respond_to do |format|
        format.json
      end
    else
      render :template => "users/show"
    end
  end

  def destroy
    relationship =  Relationship.find(params[:id])
    relationship.destroy
    redirect_to controller: 'users', action: 'index'
  end

  private

  def create_params
    params.permit(:following_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @relationship = Relationship.new
  end

  # def following
  #   @user  = User.find(params[:id])
  #   @users = @user.following
  #   render 'show_follow'
  # end

  # def followers
  #   @user  = User.find(params[:id])
  #   @users = @user.followers
  #   render 'show_follower'
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Matching
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
  %script{:src => "http://cdn.jsdelivr.net/mojs/latest/mo.min.js"}

app/views/layouts/test.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
    %script{:src => "http://cdn.jsdelivr.net/mojs/latest/mo.min.js"}
  %body

app/views/likes/create.js.erb
$('#like_button').html("<%= j(render partial: 'like', locals: { prototype: @prototype, like: @like}) %>")

app/views/likes/create.js.haml
$('#like_button').html("#{j(render partial: 'like', locals: { prototype: @prototype, like: @like})}")

app/views/matching/index.html.haml
= render 'partial/navbar'
.container
  .col-md-3
    = render 'partial/verticalnavbar'
  .col-md-9
    .panel.panel-default
      .panel-heading
        .text-center
          %span{style: "font-size:18px;"} ユーザー一覧
      - @users.each do |user|
        .col-sm-4.col-md-3
          .panel.panel-default
            .panel-heading
              %h1.panel-title= link_to "#{user.email}",  user_path(user.id)
            .panel-body
            .thumbnail
              = image_tag(user.avatar)
            .panel-footer
              .btn.btn-info.message
                = link_to 'メッセージを送る', message_path(user), class: "message_link"

app/views/matching/like.html.haml
= render 'partial/navbar'
.container
  .col-md-3
    / vertical-navbar
    = render 'partial/verticalnavbar'
  .col-md-9
    .panel.panel-default
      .panel-heading
        .text-center
          %span{:style => "font-size:18px;"} ユーザー一覧
      - @users.each do |user|
        .col-sm-4.col-md-3
          .panel.panel-default
            .panel-heading
              %h1.panel-title= link_to "#{user.email}",  user_path(user.id)
            .panel-body
            .thumbnail
              = image_tag(user.avatar)
            .panel-footer
              

app/views/matching/liked.html.haml
= render 'partial/navbar'
.container
  .col-md-3
    / vertical-navbar
    = render 'partial/verticalnavbar'
  .col-md-9
    .panel.panel-default
      .panel-heading
        .text-center
          %span{:style => "font-size:18px;"} ユーザー一覧
      - @users.each do |user|
        .col-sm-4.col-md-3
          .panel.panel-default
            .panel-heading
              %h1.panel-title= link_to "#{user.email}",  user_path(user.id)
            .panel-body
            .thumbnail
              = image_tag(user.avatar)
            .panel-footer

app/views/messages/create.js.haml
\// $(".my-message").append('
%br>/
' + '
.chat-message__name>
  ' + '#{image_tag(@message.user.avatar, class: "message-avatar")}' + '#{@message.body}' + '
');




\//
%br/
\//
.chat-message__name
  \//   #{image_tag(@message.user.avatar, class: "message-avatar")}
  \//   #{@message.body}
  \//

app/views/messages/show.html.haml
/ .chat
/   .chat-main
/     .chat-body
/       %ul.chat-messages
/         - @messages.each do |message|
/           %li.chat-message
/             .chat-message__header.clearfix
/               %p.chat-message__name
/                 = message.user.nickname
/               %p.chat-message__time
/                 = message.created_at
/               %p.chat-message__body
/                 = message.body
/     .chat-footer
/       = form_for @message, class: 'clearfix' do |f|
/         .chat-footer__body
/           = f.text_area :body, row: 1, placeholder: 'type a message'
/           %label.chat-footer__file
/             avatar
/             %i.fa.fa-image
/           = f.submit 'Send'

.chat
  .chat-main
    .chat-body
      .my-message.clearfix
        / - @my_messages.each do |message|
        /   %br.chat-message
        /     %br.chat-message__name#my_message
        /       = image_tag message.user.avatar, class: "message-avatar"
        /       = message.body
      %ul.chat-messages
        - @messages.each do |message|
          %li.chat-message.clearfix
            - if message.user == current_user
              .chat-message__header.clearfix.right_space
                .chat-message__name
                .chat-message__body
                  %span.text-left= message.body
                  = image_tag message.user.avatar, class: "message-avatar"
            - else
              .chat-message__header.clearfix 
                .chat-message__name
                  = image_tag message.user.avatar, class: "message-avatar"
                .chat-message__body.text-right
                  = message.body
    .chat-footer
      = form_for @message, html: { class: 'form js-form' } do |f|
        .chat-footer__body
          = f.text_area :body, class: "text-field", row: 1, placeholder: 'type a message'
        = f.submit 'Send'


/ <script type='text/javascript'>
/ (function(){
/ var t = setInterval(function(){
/ location.reload(true);
/ }, 5000);
/ })();
/ </script>

app/views/partial/_navbar.html.haml
%nav.navbar.navbar-devise
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Brand
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if (user_signed_in?)
          / ログインしている時
          %li= link_to "シッターになる"
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %span.caret
            %ul.dropdown-menu
              %li= link_to "プロフィール", user_path(current_user)
              %li= link_to "プロフィール編集",  edit_user_registration_path
              %li= link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          %li= link_to "シッターになる", '#'
          %li= link_to "シッターになる", '#'
          %li= link_to "シッターになる", '#'
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %span.caret
            %ul.dropdown-menu
              %li ddd
              %li ddd
              %li ddd
    / /.navbar-collapse
  / /.container-fluid

app/views/partial/_verticalnavbar.html.haml
.sidebar-nav
  .navbar.navbar-default{:role => "navigation"}
    .navbar-header
      %button.navbar-toggle{"data-target" => ".sidebar-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %label{:style => "color: #fff;"} メニュー
    .navbar-collapse.collapse.sidebar-navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "マッチング済", matching_index_path, class: "btn btn-default btn-full"
        %li= link_to "いいね済", like_path, class: "btn btn-default btn-full"
        %li= link_to "いいねされた", liked_path, class: "btn btn-default btn-full"
    / /.nav-collapse

app/views/relationships/create.js.haml
$("#follow_form").html(`
.btn.btn-default> いいね済
`)

app/views/users/_follow.html.haml
= form_with model: relationship, class: 'like_form' do |f|
    %div= hidden_field_tag :following_id, @user.id
    = f.submit "いいね", class: "btn btn-primary"

app/views/users/_follow_form.haml
#follow_form
  - if current_user.following?(@user)
    = render 'unfollow'
  - else
    = render 'follow'

app/views/users/_unfollow.html.haml
.btn.btn-default
  いいね済

app/views/users/index.html.haml
= render 'partial/navbar'
.container
  .col-md-3
    / vertical-navbar
    = render 'partial/verticalnavbar'
  .col-md-9
    .panel.panel-default
      .panel-heading
        .text-center
          %span{:style => "font-size:18px;"} ユーザー一覧
      - @users.each do |user|
        .col-sm-4.col-md-3
          .panel.panel-default
            .panel-heading
              %h1.panel-title= link_to "#{user.email}",  user_path(user)
            .panel-body
            .thumbnail
              = image_tag(user.avatar)
            .panel-footer
              = user.nickname

app/views/users/show.html.haml
.text-center
	= image_tag @user.avatar, class: "avatar"
.text-center#user-description
	= @user.nickname
	- if user_signed_in?
		#follow_form
			- if current_user.following?(@user)
				#liked.btn.btn-default いいね済
			- else
				= render 'follow', {relationship: @relationship}
	%br= @user.profile
#wrap
	#left-bg
	#right-bg

app/views/users/show_follow.haml
- @user.following.each do |user|
  %table
    %tr
      %td
        = user.name
      %td= link_to '詳細', user_path(user)

app/views/users/show_follower.haml
- @user.followers.each do |user|
  %table
    %tr
      %td
        = user.name
      %td= link_to '詳細', user_path(user)